// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System.ComponentModel.DataAnnotations;

namespace MangaWorkflow.BusinessObject.Shared.Models.HuyNQ;

public partial class ChapterHuyNq
{
    [Key]
    public int HuynqId { get; set; }

    public int? ChapterMetaHuynqId { get; set; }

    public string Title { get; set; }

    public int? ChapterNumber { get; set; }

    public int? PageCount { get; set; }

    public bool? Approved { get; set; }

    public DateTime? ReleaseDate { get; set; }

    public int? PriorityLevel { get; set; }

    public string EditorComment { get; set; }

    public string LayoutVersion { get; set; }

    public string ReviewNotes { get; set; }

    public virtual ChapterMetaHuyNq ChapterMetaHuynq { get; set; }
}