// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MangaWorkflow.BusinessObject.Shared.Models.HuyNQ;

public partial class ChapterMetaHuyNq
{
    public int HuynqId { get; set; }

    public string Code { get; set; }

    public string Description { get; set; }

    public virtual ICollection<ChapterHuyNq> ChapterHuyNqs { get; set; } = new List<ChapterHuyNq>();
}